### ISSUE TITLE
WolvenKit freezes constantly when trying to add required files

### ISSUE THREAD

**Issue by stevejackson** [seveibar/cyberpunk-2077-mandarin-chinese-anki#5]
This is really an issue with WolvenKit, so my apologies for posting it here - feel free to close this!

I've been trying off and on for months to try and solve this, with different versions of wolvenkit, cyberpunk, etc. But every time I try and add any moderately large folder to the project, WolvenKit basically hard freezes. I think it's still working in the background sometimes, but it's just... frozen. And for the larger folders I've waited for several hours with no results, until I close WolvenKit and reopen.. I think it has partially added some of the files but didn't finish.

Has anyone else run into this? Any ideas? Pretty much my only thought at this point is to leave it open overnight for each folder, but it's tough - the app is just so incredibly unresponsive once the project has a large folder in it.

FWIW, I'm running this on a pretty high end gaming PC, on an SSD, so I wouldn't think that'd be an issue.

**Comment by seveibar** [comment]
yea i mean if anyone wants to chime in feel free, but it's just a dep of this project, i don't run windows or use it regularly :) best of luck
